#version: '3.8'
#services:
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    networks:
#      - todo-network
#
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "5500:80"
#    networks:
#      - todo-network
#
#networks:
#  todo-network:
#    driver: bridge





#
#version: '3.8'
#services:
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"  # Exposing backend's port 8080
#    networks:
#      - todo-network
#    container_name: todo-backend  # Name for the backend container
#
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "5500:80"  # Exposing frontend's port 80 (mapped to port 5500 on host)
#    networks:
#      - todo-network
#    container_name: todo-frontend  # Name for the frontend container
#
#networks:
#  todo-network:
#    driver: bridge





version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-backend:latest
    ports:
      - "8080:8080"  # Exposing backend's port 8080
    networks:
      - todo-network
    container_name: todo-backend  # Name for the backend container

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: todo-frontend:latest
    ports:
      - "5500:80"  # Exposing frontend's port 80 (mapped to port 5500 on host)
    networks:
      - todo-network
    container_name: todo-frontend  # Name for the frontend container

networks:
  todo-network:
    driver: bridge